version: '4'

services:
  postgres:
    image: postgres:12.3
    container_name: car-service-postgres
    restart: always
    environment:
      POSTGRES_DB: car_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
